; VARIABLES
ORG 1000h
  MSJ DB "INGRESE UN NUMERO DE UN DIGITO"
  FIN_MSJ DB ?
  NUM DB ?
  MSJ_FALSO DB "CARACTER NO VALIDO"
  FIN_MSJ_FALSO DB ?

ORG 3000h
ES_NUM: MOV CX, 00h
  MOV AL, [BX]
  CMP AL, 30h
  JS FALSO
  CMP AL, 3Ah
  JNS FALSO
  MOV CX, 0FFh
FALSO: RET
  
ORG 2000h
  ; Imprimo mensaje
  MOV BX, OFFSET MSJ
  MOV AL, OFFSET FIN_MSJ - OFFSET MSJ
  INT 7
  ; Leo un numero
  MOV BX, OFFSET NUM
  INT 6
  ; Valido
  CALL ES_NUM
  CMP CX, 00h
  JNZ FIN_PROGRAMA
  MOV BX, OFFSET MSJ_FALSO
  MOV AL, OFFSET FIN_MSJ_FALSO - OFFSET MSJ_FALSO
  INT 7
FIN_PROGRAMA: INT 0
END

