DATO EQU 40h
ESTADO EQU 41h

ORG 1000h
  MSJ DB "INGENIERIA E INFORMATICA"
  FIN_MSJ DB ?

ORG 2000h
  ; Configuro el estado por POLLING
  IN AL, ESTADO
  AND AL, 07Fh ; 0111 1111
  OUT ESTADO, AL
  ; Configuro programa
  MOV BX, OFFSET MSJ
POLL: IN AL, ESTADO
  AND AL, 1
  JNZ POLL
  MOV AL, [BX]
  OUT DATO, AL
  INC BX
  CMP BX, OFFSET FIN_MSJ
  JNZ POLL
  LOOP: JMP LOOP
  INT 0
END