EOI EQU 20h
IMR EQU 21h
INT2 EQU 26h
ID_HAND EQU 10
ID_HAND2 EQU 15
DATO EQU 40h
ESTADO EQU 41h

ORG 40
IP_HAND DW RUT_HAND

ORG 60
IP_HAND2 DW RUT_HAND2

ORG 1000h
  MSJ DB "Ingrese 5 caracteres: "
  FIN_MSJ DB ?
  CANT DB 5
  CAD DB ?

ORG 3000h
RUT_HAND: PUSH AX
  MOV AL, [BX]
  OUT DATO, AL
  INC BX
  DEC DL
  JNZ FIN
  MOV AL, 0FFh
  OUT IMR, AL
FIN: MOV AL, EOI
  OUT EOI, AL
  POP AX
  IRET

RUT_HAND2: PUSH AX
  MOV AL, [BX]
  OUT DATO, AL
  DEC BX
  DEC DL
  JNZ FIN2
  MOV AL, 0FFh
  OUT IMR, AL
FIN2: MOV AL, EOI
  OUT EOI, AL
  POP AX
  IRET

ORG 2000h
  MOV BX, OFFSET MSJ
  MOV AL, OFFSET FIN_MSJ - OFFSET MSJ
  INT 7
  MOV BX, OFFSET CAD
  MOV DL, CANT
OTRO: INT 6
  INC BX
  DEC DL
  JNZ OTRO
  CLI
    MOV AL, 0FBh ; 1111 1011
    OUT IMR, AL
    MOV AL, ID_HAND
    OUT INT2, AL
    ; Configuro HAND por interrupcion
    MOV AL, 80h
    OUT ESTADO, AL
    MOV DL, CANT
    MOV BX, OFFSET CAD
  STI
  LOOP: CMP DL, 0
  JNZ LOOP
  CLI
    MOV AL, ID_HAND2
    OUT INT2, AL
    MOV AL, 0FBh ; 1111 1011
    OUT IMR, AL
    DEC BX
    MOV DL, CANT
  STI
  LOOP2: CMP DL, 0
  JNZ LOOP2
  ; Desactivo Handshake por interrupcion
  IN AL, ESTADO
  AND AL, 07Fh ; 0111 1111
  OUT ESTADO, AL
INF: JMP INF
  INT 0
END