; variables
ORG 1000h
  CANT DB 4
  CLAVE_PRED DB "Pas5"
  FIN_CLAVE_PRED DB ?
  CLAVE DB ?

ORG 1500
  MSJ DB "INGRESE UNA CLAVE DE 4 CARACTERES: "
  FIN_MSJ DB ?
  PERMITIDO DB "ACCESO PERMITIDO"
  FIN_PERMITIDO DB ?
  DENEGADO DB "ACCESO DENEGADO"
  FIN_DENEGADO DB ?
  
ORG 2000h
  MOV BX, OFFSET MSJ
  MOV AL, OFFSET FIN_MSJ - OFFSET MSJ
  INT 7
  ; Leo la clave
  MOV CL, 4
  MOV BX, OFFSET CLAVE
OTRO: INT 6
  INC BX
  DEC CL
  JNZ OTRO
  ; Comparo la clave
  MOV AX, OFFSET CLAVE_PRED
  MOV CX, OFFSET CLAVE
LOOP: MOV BX, AX
  MOV DH, [BX] 
  MOV BX, CX
  MOV DL, [BX]
  CMP DH, DL
  JNZ NO_ES_IGUAL
  INC AX
  INC CX
  DEC CANT
  JZ TERMINO
  JMP LOOP
TERMINO: MOV BX, OFFSET PERMITIDO
  MOV AL, OFFSET FIN_PERMITIDO - OFFSET PERMITIDO
  INT 7
  JMP FIN
NO_ES_IGUAL: MOV BX, OFFSET DENEGADO
  MOV AL, OFFSET FIN_DENEGADO - OFFSET DENEGADO
  INT 7
FIN: INT 0
END