; VARIABLES
ORG 1000h
  NUM1_A DW 3000H
  NUM1_B DW 2000H
  NUM2_A DW 5000H
  NUM2_B DW 1000H
  RES_A DW ?
  RES_B DW ?

ORG 3000h
SUM32: MOV BX, SP
  ADD BX, 12
  MOV AX, [BX] ; NUM1_A
  SUB BX, 2
  ADD AX, [BX] ; RES PARTE A -> AX
  SUB BX, 2
  MOV CX, [BX] ; NUM1_B
  SUB BX, 2
  ADD CX, [BX] ; RES PARTE B -> CX
  SUB BX, 2

  MOV DX, [BX] ; DIR RES_A
  PUSH BX      ; BACKUP BX
  MOV BX, DX
  MOV [BX], AX ; GUARDO LA PARTE A DEL RESULTADO
  POP BX
  SUB BX, 2
  MOV DX, [BX] ; DIR RES_B
  MOV BX, DX
  MOV [BX], CX ; GUARDO LA PARTE B DEL RESULTADO
  RET

ORG 2000h
  MOV AX, NUM1_A
  PUSH AX
  MOV AX, NUM2_A
  PUSH AX
  MOV AX, NUM1_B
  PUSH AX
  MOV AX, NUM2_B
  PUSH AX
  MOV AX, OFFSET RES_A
  PUSH AX
  MOV AX, OFFSET RES_B
  PUSH AX
  CALL SUM32
  HLT
END


